version: '3.9'

services:
  database:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      # Pointer vers un dossier qui aura des scripts d'initialisation de notre base
      - ./database/dev-initdb.d:/docker-entrypoint-initdb.d
      # Ajouter le DDL qui va tourner en dernier
      - ./database/ddl/ddl.sql:/docker-entrypoint-initdb.d/999-ddl.sql
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-MT5_back_project}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MARIADB_ROOT_PASSWORD" ]
      interval: 5s
      timeout: 5s
      retries: 5