version: '3.9'

services:
  database:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      # Pointer vers un dossier qui aura des scripts d'initialisation de notre base
      - ./database/dev-initdb.d:/docker-entrypoint-initdb.d
      # Ajouter le DDL qui va tourner en dernier
      - ./database/ddl/ddl.sql:/docker-entrypoint-initdb.d/999-ddl.sql
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: MT5_back_project
      MARIADB_USER: louis
      MARIADB_PASSWORD: louis_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  go-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    environment:
        MARIADB_ROOT_PASSWORD: password
        MARIADB_DATABASE: MT5_back_project
        MARIADB_USER: louis
        MARIADB_PASSWORD: louis_password
    ports:
        - "8097:8097"
    depends_on:
        database:
            condition: service_healthy

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"